(function(){/*
 MIT License (c) copyright 2010-2013 B Cavalier & J Hann */
window.vtex||(window.vtex={});
(function(p){function u(){}function t(a,b){return 0==X.call(a).indexOf("[object "+b)}function y(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function k(a,b){var d,c,e,f;d=1;c=a;"."==c.charAt(0)&&(e=!0,c=c.replace(Y,function(a,b,c,e){c&&d++;return e||""}));if(e){e=b.split("/");f=e.length-d;if(0>f)return a;e.splice(f,d);return e.concat(c||[]).join("/")}return c}function J(a){var b=a.indexOf("!");return{f:a.substr(b+1),d:0<=b&&a.substr(0,b)}}function B(){}function m(a,b){B.prototype=
a||P;var d=new B;B.prototype=P;for(var c in b)d[c]=b[c];return d}function K(){function a(a,b,d){c.push([a,b,d])}function b(a,b){for(var d,e=0;d=c[e++];)(d=d[a])&&d(b)}var d,c,e;d=this;c=[];e=function(d,g){a=d?function(a){a&&a(g)}:function(a,b){b&&b(g)};e=u;b(d?0:1,g);b=u;c=l};this.then=function(b,c,e){a(b,c,e);return d};this.resolve=function(a){d.ma=a;e(!0,a)};this.reject=function(a){d.la=a;e(!1,a)};this.s=function(a){b(2,a)}}function L(a){return a instanceof K||a instanceof C}function v(a,b,d,c){L(a)?
a.then(b,d,c):b(a)}function D(a,b,d){var c;return function(){0<=--a&&b&&(c=b.apply(l,arguments));0==a&&d&&d(c);return c}}function A(){var a,b;E="";a=[].slice.call(arguments);t(a[0],"Object")&&(b=a.shift(),b=M(b));return new C(a[0],a[1],a[2],b)}function M(a,b,d){var c;E="";if(a&&(h.M(a),w=h.a(a),"preloads"in a&&(c=new C(a.preloads,l,d,F,!0),h.j(function(){F=c})),a=a.main))return new C(a,b,d)}function C(a,b,d,c,e){var f;f=h.h(w,l,[].concat(a),e);this.then=this.then=a=function(a,b){v(f,function(b){a&&
a.apply(l,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(a,b,c){return new C(a,b,c,f)};this.config=M;(b||d)&&a(b,d);h.j(function(){v(e||F,function(){v(c,function(){h.o(f)},d)})})}function T(a){var b,d;b=a.id;b==l&&(G!==l?G={C:"Multiple anonymous defines encountered"}:(b=h.Z())||(G=a));if(b!=l){d=n[b];b in n||(d=h.g(b,w),d=h.w(d.a,b),n[b]=d);if(!L(d))throw Error("duplicate define: "+b);d.aa=!1;h.A(d,a)}}function Q(){var a=h.W(arguments);T(a)}var E,w,x,H,z=window.document,
R=z&&(z.head||z.getElementsByTagName("head")[0]),Z=R&&R.getElementsByTagName("base")[0]||null,U={},V={},N={},$="addEventListener"in p?{}:{loaded:1,complete:1},P={},X=P.toString,l,n={},O={},F=!1,G,W=/^\/|^[^:]+:\/\//,Y=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,aa=/\/\*[\s\S]*?\*\/|\/\/.*?[\n\r]/g,ba=/require\s*\(\s*(["'])(.*?[^\\])\1\s*\)|[^\\]?(["'])/g,ca=/\s*,\s*/,S,h;h={k:function(a,b,d){var c;a=k(a,b);if("."==a.charAt(0))return a;c=J(a);a=(b=c.d)||c.f;a in d.c&&(a=d.c[a].I||a);b&&(0>b.indexOf("/")&&!(b in
d.c)&&(a=y(d.K)+"/"+b),a=a+"!"+c.f);return a},h:function(a,b,d,c){function e(b,c){var d,f;d=h.k(b,g.id,a);if(!c)return d;f=J(d);if(!f.d)return d;d=n[f.d];f.f="normalize"in d?d.normalize(f.f,e,g.a)||"":e(f.f);return f.d+"!"+f.f}function f(b,d,f){var r;r=d&&function(a){d.apply(l,a)};if(t(b,"String")){if(r)throw Error("require(id, callback) not allowed");f=e(b,!0);b=n[f];if(!(f in n))throw Error("Module not resolved: "+f);return(f=L(b)&&b.b)||b}v(h.o(h.h(a,g.id,b,c)),r,f)}var g;g=new K;g.id=b||"";g.$=
c;g.B=d;g.a=a;g.t=f;f.toUrl=function(b){return h.g(e(b,!0),a).url};g.k=e;return g},w:function(a,b,d){var c,e,f;c=h.h(a,b,l,d);e=c.resolve;f=D(1,function(a){c.n=a;try{return h.Q(c)}catch(b){c.reject(b)}});c.resolve=function(a){v(d||F,function(){e(n[c.id]=O[c.url]=f(a))})};c.D=function(a){v(d||F,function(){c.b&&(f(a),c.s(V))})};return c},P:function(a,b,d,c){return h.h(a,d,l,c)},Y:function(a){return a.t},F:function(a){return a.b||(a.b={})},X:function(a){var b=a.p;b||(b=a.p={id:a.id,uri:h.G(a),exports:h.F(a),
config:function(){return a.a}},b.b=b.exports);return b},G:function(a){return a.url||(a.url=h.v(a.t.toUrl(a.id),a.a))},M:function(a){var b,d,c,e,f;b="curl";d="define";c=e=p;if(a&&(f=a.overwriteApi||a.ja,b=a.apiName||a.ca||b,c=a.apiContext||a.ba||c,d=a.defineName||a.ea||d,e=a.defineContext||a.da||e,x&&t(x,"Function")&&(p.curl=x),x=null,H&&t(H,"Function")&&(p.define=H),H=null,!f)){if(c[b]&&c[b]!=A)throw Error(b+" already exists");if(e[d]&&e[d]!=Q)throw Error(d+" already exists");}c[b]=A;e[d]=Q},a:function(a){function b(a,
b){var d,c,g,q,s;for(s in a){g=a[s];t(g,"String")&&(g={path:a[s]});g.name=g.name||s;q=e;c=J(y(g.name));d=c.f;if(c=c.d)q=f[c],q||(q=f[c]=m(e),q.c=m(e.c),q.e=[]),delete a[s];c=g;var n=b,I=void 0;c.path=y(c.path||c.location||"");n&&(I=c.main||"./main","."==I.charAt(0)||(I="./"+I),c.I=k(I,c.name+"/"));c.a=c.config;c.a&&(c.a=m(e,c.a));c.N=d.split("/").length;d?(q.c[d]=c,q.e.push(d)):q.l=h.L(g.path,e)}}function d(a){var b=a.c;a.J=new RegExp("^("+a.e.sort(function(a,c){return b[c].N-b[a].N}).join("|").replace(/\/|\./g,
"\\$&")+")(?=\\/|$)");delete a.e}var c,e,f,g;"baseUrl"in a&&(a.l=a.baseUrl);"main"in a&&(a.I=a.main);"preloads"in a&&(a.ka=a.preloads);"pluginPath"in a&&(a.K=a.pluginPath);if("dontAddFileExt"in a||a.i)a.i=new RegExp(a.dontAddFileExt||a.i);c=w;e=m(c,a);e.c=m(c.c);f=a.plugins||{};e.plugins=m(c.plugins);e.r=m(c.r,a.r);e.q=m(c.q,a.q);e.e=[];b(a.packages,!0);b(a.paths,!1);for(g in f)a=h.k(g+"!","",e),e.plugins[a.substr(0,a.length-1)]=f[g];f=e.plugins;for(g in f)if(f[g]=m(e,f[g]),a=f[g].e)f[g].e=a.concat(e.e),
d(f[g]);for(g in c.c)e.c.hasOwnProperty(g)||e.e.push(g);d(e);return e},g:function(a,b){var d,c,e,f;d=b.c;e=W.test(a)?a:a.replace(b.J,function(a){c=d[a]||{};f=c.a;return c.path||""});return{a:f||w,url:h.L(e,b)}},L:function(a,b){var d=b.l;return d&&!W.test(a)?y(d)+"/"+a:a},v:function(a,b){return a+((b||w).i.test(a)?"":".js")},H:function(a,b,d){var c=z.createElement("script");c.onload=c.onreadystatechange=function(d){d=d||p.event;if("load"==d.type||$[c.readyState])delete N[a.id],c.onload=c.onreadystatechange=
c.onerror="",b()};c.onerror=function(){d(Error("Syntax or http error: "+a.url))};c.type=a.ga||"text/javascript";c.charset="utf-8";c.async=!a.ia;c.src=a.url;N[a.id]=c;R.insertBefore(c,Z);return c},R:function(a){var b=[],d;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(aa,"").replace(ba,function(a,e,f,g){g?d=d==g?l:d:d||b.push(f);return""});return b},W:function(a){var b,d,c,e,f,g;f=a.length;c=a[f-1];e=t(c,"Function")?c.length:-1;2==f?t(a[0],"Array")?d=a[0]:b=a[0]:3==f&&(b=a[0],
d=a[1]);!d&&0<e&&(g=!0,d=["require","exports","module"].slice(0,e).concat(h.R(c)));return{id:b,n:d||[],u:0<=e?c:function(){return c},m:g}},Q:function(a){var b;b=a.u.apply(a.m?a.b:l,a.n);b===l&&a.b&&(b=a.p?a.b=a.p.exports:a.b);return b},A:function(a,b){a.u=b.u;a.m=b.m;a.B=b.n;h.o(a)},o:function(a){function b(a,b,c){g[b]=a;c&&m(a,b)}function d(b,c){var d,e,f,g;d=D(1,function(a){e(a);r(a,c)});e=D(1,function(a){m(a,c)});f=h.T(b,a);(g=L(f)&&f.b)&&e(g);v(f,d,a.reject,a.b&&function(a){f.b&&(a==U?e(f.b):
a==V&&d(f.b))})}function c(){a.resolve(g)}var e,f,g,n,k,m,r;g=[];f=a.B;n=f.length;0==f.length&&c();m=D(n,b,function(){a.D&&a.D(g)});r=D(n,b,c);for(e=0;e<n;e++)k=f[e],k in S?(r(S[k](a),e,!0),a.b&&a.s(U)):k?d(k,e):r(l,e,!0);return a},U:function(a){h.G(a);h.H(a,function(){var b=G;G=l;!1!==a.aa&&(!b||b.C?a.reject(Error(b&&b.C||"define() missing or duplicated: "+a.url)):h.A(a,b))},a.reject);return a},T:function(a,b){var d,c,e,f,g,k,m,l,r,p,q,s;d=b.k;c=b.$;e=b.a||w;g=d(a);g in n?k=g:(f=J(g),l=f.f,k=f.d||
l,r=h.g(k,e));if(!(g in n))if(s=h.g(l,e).a,f.d)m=k;else if(m=s.moduleLoader||s.ha||s.loader||s.fa)l=k,k=m,r=h.g(m,e);k in n?p=n[k]:r.url in O?p=n[k]=O[r.url]:(p=h.w(s,k,c),p.url=h.v(r.url,r.a),n[k]=O[r.url]=p,h.U(p));k==m&&(f.d&&e.plugins[f.d]&&(s=e.plugins[f.d]),q=new K,v(p,function(a){var b,e,f;f=a.dynamic;l="normalize"in a?a.normalize(l,d,p.a)||"":d(l);e=m+"!"+l;b=n[e];if(!(e in n)){b=h.P(s,e,l,c);f||(n[e]=b);var g=function(a){f||(n[e]=a);b.resolve(a)};g.resolve=g;g.reject=g.error=b.reject;a.load(l,
b.t,g,s)}q!=b&&v(b,q.resolve,q.reject,q.s)},q.reject));return q||p},Z:function(){var a;if(!t(p.opera,"Opera"))for(var b in N)if("interactive"==N[b].readyState){a=b;break}return a},V:function(a){var b=0,d,c;for(d=z&&(z.scripts||z.getElementsByTagName("script"));d&&(c=d[b++]);)if(a(c))return c},S:function(){var a,b="";(a=h.V(function(a){(a=a.getAttribute("data-curl-run"))&&(b=a);return a}))&&a.setAttribute("data-curl-run","");return b},O:function(){function a(){h.H({url:c.shift()},b,b)}function b(){E&&
(c.length?(h.j(d),a()):d("run.js script did not run."))}function d(a){throw Error(a||"Primary run.js failed. Trying fallback.");}var c=E.split(ca);c.length&&a()},j:function(a){setTimeout(a,0)}};S={require:h.Y,exports:h.F,module:h.X};A.version="0.8.10";A.config=M;Q.amd={plugins:!0,jQuery:!0,curl:"0.8.10"};w={l:"",K:"curl/plugin",i:/\?|\.js\b/,r:{},q:{},plugins:{},c:{},J:/$^/};x=p.curl;H=p.define;x&&t(x,"Object")?(p.curl=l,M(x)):h.M();(E=h.S())&&h.j(h.O);n.curl=A;n["curl/_privileged"]={core:h,cache:n,
config:function(){return w},_define:T,_curl:A,Promise:K}})(this.window.vtex||"undefined"!=typeof global&&global||this);
(function(p){var u=p.document,t=/^\/\//,y;u&&(y=u.head||(u.head=u.getElementsByTagName("head")[0]));define=vtex.define||window.define;define("curl/plugin/link",{load:function(k,p,B,m){k=p.toUrl(k);k=k.lastIndexOf(".")<=k.lastIndexOf("/")?k+".css":k;m=k=(m="fixSchemalessUrls"in m?m.fixSchemalessUrls:u.location.protocol)?k.replace(t,m+"//"):k;k=u.createElement("link");k.rel="stylesheet";k.type="text/css";k.href=m;y.appendChild(k);B(k.sheet||k.styleSheet)}})})(this.window.vtex||"undefined"!=typeof global&&
global||this);
}).call(this);
